name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: v
categories:
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
  - title: 'Maintenance'
    label: 'chore'
autolabeler:
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'fix'
    branch:
      - '/bugfix\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
template: |
  ## Changes

  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION