data-transfer:
  data-type-mappings:
    destination:
      postgres:
        SMALLINT: [smallint, short, int16]
        INTEGER: [int, integer, int32]
        BIGINT: [long, bigint, int64, timestamp]
        REAL: [float, real]
        DOUBLE PRECISION: [double, double precision]
        TEXT: [text, string, varchar, character varying]
        BOOLEAN: [boolean, bool]
        BYTEA: [blob, bytea, binData]
        TIMESTAMP WITH TIME ZONE: [date]
      mongo:
        double: [float, real, double precision]
        string: [text, varchar, character varying, symbol, objectid, uuid]
        bool: [boolean]
        date: [timestamp, timestamptz, timestamp with time zone, timestamp without time zone, date, time, time with time zone, time without time zone]
        int: [integer, int32, smallint, short, int16]
        long: [bigint, int64]
        binData: [bindata, blob, bytea]
        object: []
        array: []
        decimal: [decimal128]
